// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial2Diferido;

namespace Parcial2Diferido.Migrations
{
    [DbContext(typeof(DBAdminContext))]
    [Migration("20210609163602_change1")]
    partial class change1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parcial2Diferido.Model.Facultad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("facultad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("Parcial2Diferido.Model.Pregunta", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("pregunta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Preguntas");
                });

            modelBuilder.Entity("Parcial2Diferido.Model.Solicitud", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_facultadid")
                        .HasColumnType("int");

                    b.Property<int?>("id_usuarioid")
                        .HasColumnType("int");

                    b.Property<bool>("vigente")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.HasIndex("id_facultadid");

                    b.HasIndex("id_usuarioid");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("Parcial2Diferido.Model.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("contrasena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<int?>("id_preguntaid")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("residencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("respuesta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("id_preguntaid");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Parcial2Diferido.Model.Solicitud", b =>
                {
                    b.HasOne("Parcial2Diferido.Model.Facultad", "id_facultad")
                        .WithMany()
                        .HasForeignKey("id_facultadid");

                    b.HasOne("Parcial2Diferido.Model.Usuario", "id_usuario")
                        .WithMany()
                        .HasForeignKey("id_usuarioid");

                    b.Navigation("id_facultad");

                    b.Navigation("id_usuario");
                });

            modelBuilder.Entity("Parcial2Diferido.Model.Usuario", b =>
                {
                    b.HasOne("Parcial2Diferido.Model.Pregunta", "id_pregunta")
                        .WithMany()
                        .HasForeignKey("id_preguntaid");

                    b.Navigation("id_pregunta");
                });
#pragma warning restore 612, 618
        }
    }
}
